name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Gradle Lint
      run: ./gradlew lint
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.1.0
      with:
      # GITHUB_TOKEN.
      github_token: # optional, default is ${{ github.token }}
      # Report level for reviewdog [info,warning,error]
      level: # optional, default is info
      # Reporter of reviewdog command [github-pr-check,github-pr-review]
      reporter: # optional, default is github-pr-check
      # Checkstyle config file
      checkstyle_config: # default is google_checks.xml
